from tabular.constants import BATCH_SIZE

TABULAR_LAYERS = 6
WEIGHT_DECAY = 0.001
BASE_LR = 0.00005
TEXTUAL_UNFREEZE_LAYERS = 6
PRETRAIN_GLOBAL_BATCH_SIZE = 128
MAX_EPOCH_EXAMPLES = 2048
PRETRAIN_VAL_RATIO = 0.05


if MAX_EPOCH_EXAMPLES % BATCH_SIZE != 0:
    raise ValueError(f"MAX_EPOCH_EXAMPLES must be divisible by {BATCH_SIZE}")